<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpShift.Inventory.Core\SharpShift.Inventory.Core.csproj" />
    <ProjectReference Include="..\SharpShift.Inventory.Cli\SharpShift.Inventory.Cli.csproj" />
    <ProjectReference Include="..\SharpShift.Inventory.Discovery\SharpShift.Inventory.Discovery.csproj" />
    <ProjectReference Include="..\SharpShift.Inventory.ProjectAnalysis\SharpShift.Inventory.ProjectAnalysis.csproj" />
    <ProjectReference Include="..\SharpShift.Inventory.DependencyAnalysis\SharpShift.Inventory.DependencyAnalysis.csproj" />
  </ItemGroup>

</Project>